kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.cm.name }}
  labels:
    app: {{ .Values.app }}
data:
  default.conf: |
    upstream php-fpm {
      server php:9000;
      keepalive 16;
    }
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      index index.php index.html;
      server_name _;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
      root /var/www/html;

      location / {
        try_files $uri $uri/ /index.php$is_args$query_string;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass http://php-fpm;
        fastcgi_keep_conn on;
        fastcgi_index index.php;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }
