apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.containers.php.name }}
          image: {{ .Values.containers.php.image }}:{{ .Values.containers.php.tag }}
          ports:
            - containerPort: {{ .Values.containers.php.port }}
          env:
            - name: environment
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ .Values.pvc.volume }}
              mountPath: {{ .Values.pvc.path }}
        - name: {{ .Values.containers.nginx.name }}
          image: {{ .Values.containers.nginx.image }}:{{ .Values.containers.nginx.tag }}
          ports:
            - containerPort: {{ .Values.containers.nginx.port }}
          env:
            - name: environment
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ .Values.cm.volume }}
              mountPath: {{ .Values.cm.path }}
            - name: {{ .Values.pvc.volume }}
              mountPath: {{ .Values.pvc.path }}
      volumes:
        - name: {{ .Values.cm.volume }}
          configMap:
            name: {{ .Values.cm.name }}
        - name: {{ .Values.pvc.volume }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claim }}
