apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.containers.php.name }}
  labels:
    app: {{ .Values.containers.php.name }}
spec:
  ports:
  - port: {{ .Values.containers.php.port }}
    protocol: TCP
    targetPort: {{ .Values.containers.php.port }}
  selector:
    app: {{ .Values.app }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.containers.nginx.name }}
  labels:
    app: {{ .Values.containers.nginx.name }}
spec:
  ports:
  - port: {{ .Values.containers.nginx.port }}
    protocol: TCP
    targetPort: {{ .Values.containers.nginx.port }}
  selector:
    app: {{ .Values.app }}
  type: NodePort
