apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.path }}
          env:
            - name: environment
              value: {{ .Values.environment }}
            - name: dbname
              value: {{ .Values.db.name }}
            - name: dbrootpassword
              value: {{ .Values.db.rootpassword }}
            - name: dbuser
              value: {{ .Values.db.user }}
            - name: dbuserpassword
              value: {{ .Values.db.userpassword }}
    volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.claim }}
